/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MyBrandButton: typeof import('./../../packages/bloc-components/src/components/MyBrandButton/MyBrandButton.vue')['default']
    MyBrandInput: typeof import('./../../packages/bloc-components/src/components/MyBrandInput/MyBrandInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
